title: Academic Services

items:
  - role: Conference Reviewer
    venues: [NeurIPS 2025, NeurIPS 2026, CVPR 2026, AAAI 2025, WACV 2026]
    visibility: public

  - role: Journal Reviewer
    venues: [TPAMI, CVIU, MVAP]
    visibility: archive
